#!/bin/bash

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh
SPARKBIN="/usr/lib/spark/bin/spark-submit"

if [ ! -f ${JARFILE} ] 
then
    juju-log "Installation is not finished yet. Please restart this later"
    exit 0
fi 

if [ ! -f ${SPARKBIN} ]
then
    juju-log "Installation is not finished yet. Please restart this later"
    exit 0
fi 

juju-log "Submitting the Spark Application to the Cluster"
${SPARKBIN} --class com.zdatainc.rts.spark.SentimentAnalysis --name "Twitter Sentiment Analys" --master yarn-client "${DEST_FOLDER}/rts.spark-0.0.1.jar" &

exit 0
